openapi: 3.1.0
info:
  title: LRI Reflected Event
  version: 1.0.0
  description: Reflection / Feedback loop.

components:
  schemas:
    LRIReflectedEvent:
      type: object
      required:
        - event_id
        - timestamp
        - type
        - payload
      properties:
        event_id:
          type: string
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          const: LRI_REFLECTED
        payload:
          type: object
          properties:
            subject_id:
              type: string
            observation_window:
              type: object
              properties:
                start:
                  type: string
                  format: date-time
                end:
                  type: string
                  format: date-time
            metrics:
              type: object
              description: Calculated drift, coherence, or other reflection metrics.
            insights:
              type: string
              description: Narrative or structured insight derived from reflection.
